/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sora: ["var(--font-sora)", "system-ui", "sans-serif"],
        sans: ["var(--font-dm-sans)", "system-ui", "sans-serif"],
        "geist": ["var(--font-geist)", "Geist", "sans-serif"],
        "display-hero": ["var(--font-geist)", "Geist", "sans-serif"],
        "headline-section": ["var(--font-geist)", "Geist", "sans-serif"],
        "headline-sub": ["var(--font-geist)", "Geist", "sans-serif"],
        "badge-caps": ["var(--font-geist)", "Geist", "sans-serif"],
        "body-lg": ["DM Sans", "sans-serif"],
        "body-base": ["DM Sans", "sans-serif"],
        "label-ui": ["DM Sans", "sans-serif"],
        "body-bold": ["DM Sans", "sans-serif"],
      },
      fontSize: {
        "display-hero": ["72px", { lineHeight: "76px", letterSpacing: "-0.04em", fontWeight: "900" }],
        "headline-section": ["48px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sub": ["30px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "badge-caps": ["10px", { lineHeight: "12px", letterSpacing: "0.18em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-base": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-ui": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-bold": ["16px", { lineHeight: "24px", fontWeight: "700" }],
      },
      colors: {
        accent: "#3792E8",
        "accent-hover": "#6EB0EE",
        "dark-base": "#070719",
        "dark-secondary": "#10102D",
        "brand-bg": "#070719",
        "brand-surface": "#111124",
        "brand-primary": "#a0c9ff",
        "brand-on-primary": "#003259",
        "brand-accent": "#3792E8",
        "brand-surface-variant": "#333347",
        "brand-on-surface": "#e2e0fa",
        "brand-on-surface-variant": "#c0c7d3",
        "brand-container-low": "#1a1a2d",
        // Stitch color tokens
        "surface-tint": "#a0c9ff",
        "inverse-on-surface": "#2f2e43",
        "tertiary-container": "#8c9197",
        "error-container": "#93000a",
        "error-red": "#EF4444",
        "surface-bright": "#38374c",
        "surface-container-highest": "#333347",
        "on-surface-variant": "#c0c7d3",
        "background": "#111124",
        "surface-container-lowest": "#0c0c1f",
        "on-surface": "#e2e0fa",
        "on-secondary": "#2d2d4c",
        "secondary": "#c4c3e9",
        "surface-variant": "#333347",
        "on-primary-fixed-variant": "#00497e",
        "primary-fixed": "#d2e4ff",
        "primary-container": "#3a94ea",
        "inverse-primary": "#0061a6",
        "surface-container": "#1e1e31",
        "on-background": "#e2e0fa",
        "primary-fixed-dim": "#a0c9ff",
        "inverse-surface": "#e2e0fa",
        "surface-container-low": "#1a1a2d",
        "on-secondary-container": "#b6b5db",
        "surface-container-high": "#28283c",
        "on-tertiary-container": "#252a2f",
        "primary": "#a0c9ff",
        "outline": "#8a919d",
        "outline-variant": "#404752",
        "on-primary-fixed": "#001c37",
        "border-subtle-light": "rgba(7,7,25,0.12)",
        "secondary-container": "#464666",
        "surface": "#111124",
        "success-blue": "#185FA5",
        "surface-dim": "#111124",
        "border-subtle-dark": "rgba(255,255,255,0.1)",
        "on-primary": "#003259",
        "tertiary": "#c2c7cd",
        "accent-blue": "#3792E8",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "border-spin": {
          to: { transform: "rotate(360deg)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "border-spin": "border-spin 8s linear infinite",
      },
    },
  },
  plugins: [],
}
